import { useState, useEffect } from 'react';
import { fetchMachineStatus, type MachineStatus } from '../services/autoclaveApi';

export const useMachineStatus = (currentScreenID?: string, interval = 1000) => {
  const [data, setData] = useState<MachineStatus | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
    
  

  useEffect(() => {
    const fetchData = async () => {
      try {
        const status = await fetchMachineStatus(currentScreenID);
        console.log('fetchMachineStatus analogData', status);
        setData(status);
        setError(null);
      } catch (err) {

        setData({
            "alarms": {
                "alarm_text": [
                    "Air Failure"
                ]
            },
            "analogData": {
                "airdet_temp": "14.1",
                "chamber_pressure": "975",
                "chamber_temp": "0.0",
                "drain_temp": "12.5",
                "filter_pressure": "0",
                "filter_temp": "0.0",
                "jacket_pressure": "986",
                "load_temp": "13.0",
                "vent_temp": "14.3"
            },
            "analogVisibility": {
                "show_airdet_temp": false,
                "show_chamber_pressure": true,
                "show_chamber_temp": false,
                "show_drain_temp": false,
                "show_filter_pressure": false,
                "show_filter_temp": false,
                "show_jacket_pressure": true,
                "show_load_temp": false,
                "show_vent_temp": true
            },
            "buttonVisibility1": {
                "get_screen": 203,
                "show_accept_button": false,
                "show_alarm_button": true,
                "show_auto_wait_abort_button": false,
                "show_close_button": true,
                "show_continue_button": false,
                "show_discard_drain_button": false,
                "show_discard_end_button": false,
                "show_door_proc_abort_button": false,
                "show_keep_warm_finish_button": false,
                "show_keep_warm_lock_button": false,
                "show_keep_warm_unlock_button": false,
                "show_load_button": false,
                "show_loading_abort_button": false,
                "show_lock_button": false,
                "show_man_leak_finish_button": false,
                "show_man_leak_pump_button": false,
                "show_menu_button": true,
                "show_open_button": true,
                "show_recover_button": false,
                "show_reject_button": false,
                "show_release_button": false,
                "show_restart_button": false,
                "show_review_button": false,
                "show_start_button": true,
                "show_unloading_abort_button": false,
                "show_unlock_button": false
            },
            "buttonVisibility2": {
                "get_screen": 309,
                "show_accept_button": false,
                "show_alarm_button": true,
                "show_auto_wait_abort_button": false,
                "show_close_button": false,
                "show_continue_button": false,
                "show_discard_drain_button": false,
                "show_discard_end_button": false,
                "show_door_proc_abort_button": false,
                "show_keep_warm_finish_button": false,
                "show_keep_warm_lock_button": false,
                "show_keep_warm_unlock_button": false,
                "show_load_button": false,
                "show_loading_abort_button": false,
                "show_lock_button": false,
                "show_man_leak_finish_button": false,
                "show_man_leak_pump_button": false,
                "show_menu_button": true,
                "show_open_button": false,
                "show_recover_button": false,
                "show_reject_button": false,
                "show_release_button": false,
                "show_restart_button": false,
                "show_review_button": false,
                "show_start_button": true,
                "show_unloading_abort_button": false,
                "show_unlock_button": false
            },
            "digitalInputNames": [
                "Door 1 Closed",
                "Door 1 Safety Edge",
                "Door 1 Sealed",
                "Door 1 Bolted",
                "Door 2 Closed",
                "Door 2 Safety Edge",
                "Door 2 Sealed",
                "Door 2 Bolted",
                "Door Open Touch",
                "Door Close Touch",
                "Interlock 1",
                "Interlock 2",
                "Compressor Pressure Switch",
                "Steam OK",
                "Water OK",
                "Air OK",
                "Emergency Stop",
                "Door 1 Isolate",
                "Door 2 Isolate",
                "Steam Gen HP Option",
                "Configurable Input",
                "Vac Pump Overload",
                "Door 1 Opened",
                "Door 2 Opened",
                "Steam Gen Water Low",
                "Steam Gen Water High",
                "Steam Gen Not Up To Pres",
                "Water Tank Not Full",
                "Steam Gen Over Temp",
                "Water Tank Too Hot",
                "Chamber Over Pressure",
                "Clean Water OK",
                "Air Health OK",
                "Tank Temps Safe",
                "Dump Tank Full",
                "Shared Steam Free",
                "Manual Leak Pump Control",
                "Drain Temp OK",
                "Door In Position",
                "Blowdown Pressure Switch",
                "Vac Ready",
                "Preheat Tank Temp OK",
                "Reject Cycle",
                "Accept Cycle",
                "Auto Loader Ready",
                "Auto Loader Complete",
                "Auto Unloader Ready",
                "Auto Unloader Complete",
                "Door 1 Trace Detected",
                "Door 2 Trace Detected",
                "Interlock 3",
                "Input 52",
                "Input 53",
                "Input 54",
                "Input 55",
                "Input 56",
                "Input 57",
                "Input 58",
                "Input 59",
                "Input 60",
                "Input 61",
                "Input 62",
                "Input 63",
                "Input 64"
            ],
            "digitalInputs": [
                true,
                true,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                true,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false
            ],
            "digitalOutputs": [
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false
            ],
            "displayData": {
                "auto_start_time": "000:00:00",
                "auto_start_time:": "",
                "countdown_time": "",
                "cycle_no": "000007",
                "cycle_time": "00:01:48",
                "date": "21/01/26",
                "next_cycle_no": "000008",
                "pulse_count": "",
                "stage_name": "-",
                "stage_time": "00:00:00",
                "target_pressure": "",
                "target_temperature": "",
                "time": "15:02:54"
            },
            "displayVisibility1": {
                "get_screen": 203,
                "show_mini_cycle_and_cycle_time": false,
                "show_mini_date_time": true,
                "show_mini_next_cycle": false,
                "show_panel_auto_wait": false,
                "show_panel_contaminated": false,
                "show_panel_door_1_open": false,
                "show_panel_door_2_open": false,
                "show_panel_door_not_available": false,
                "show_panel_failed": false,
                "show_panel_fill_with_water": false,
                "show_panel_invalid_a": false,
                "show_panel_invalid_b": false,
                "show_panel_invalid_c": false,
                "show_panel_keeping_warm": false,
                "show_panel_loading": false,
                "show_panel_passed": false,
                "show_panel_restarting": false,
                "show_panel_sealing": false,
                "show_panel_stage_info": false,
                "show_panel_standby": false,
                "show_panel_tiny_closed": false,
                "show_panel_tiny_failed": false,
                "show_panel_tiny_fill_with_water": false,
                "show_panel_tiny_open": false,
                "show_panel_tiny_passed": false,
                "show_panel_tiny_water_level_ok": false,
                "show_panel_unloading": false,
                "show_panel_unsealing": false,
                "show_panel_water_level_ok": false
            },
            "displayVisibility2": {
                "get_screen": 309,
                "show_mini_cycle_and_cycle_time": false,
                "show_mini_date_time": true,
                "show_mini_next_cycle": false,
                "show_panel_auto_wait": false,
                "show_panel_contaminated": false,
                "show_panel_door_1_open": false,
                "show_panel_door_2_open": false,
                "show_panel_door_not_available": false,
                "show_panel_failed": false,
                "show_panel_fill_with_water": false,
                "show_panel_invalid_a": false,
                "show_panel_invalid_b": false,
                "show_panel_invalid_c": false,
                "show_panel_keeping_warm": false,
                "show_panel_loading": false,
                "show_panel_passed": false,
                "show_panel_restarting": false,
                "show_panel_sealing": false,
                "show_panel_stage_info": false,
                "show_panel_standby": false,
                "show_panel_tiny_closed": false,
                "show_panel_tiny_failed": false,
                "show_panel_tiny_fill_with_water": false,
                "show_panel_tiny_open": false,
                "show_panel_tiny_passed": false,
                "show_panel_tiny_water_level_ok": false,
                "show_panel_unloading": false,
                "show_panel_unsealing": false,
                "show_panel_water_level_ok": false
            },
            "forceManualBits": [
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false
            ],
            "forceOnBits": [
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false
            ],
            "programData": {
                "inCycle": false,
                "program_name": "Standard Program"
            },
            "systemConnected": true
        })

        //setError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        setLoading(false);
      }
    };

    fetchData();

    const timer = setInterval(fetchData, interval);

    return () => clearInterval(timer);
  }, [currentScreenID, interval]);

  return { data, error, loading };
};
